name: Upload lc.json
on:
  push:
    branches: ['main']
    paths: ['lc.json']
    
jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.0
        with:
          comment: "true" # enable comment mode
          files: "lc.json"

  upload:
    needs: json-yaml-validate
    runs-on: ubuntu-latest
    steps:
      - name: Upload to DO Spaces
        uses: actions/checkout@master
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key:   ${{ secrets.DO_ACCESS_KEY   }}
          secret_key:   ${{ secrets.DO_SECRET_KEY   }}
          space_name:   ${{ secrets.DO_SPACE_NAME   }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source:       lc.json
