name: Upload lc.json
on:
  push:
    branches: ['main']
    paths: ['lc.json']
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to DO Spaces
        uses: actions/checkout@master
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key:   ${{ secrets.DO_ACCESS_KEY   }}
          secret_key:   ${{ secrets.DO_SECRET_KEY   }}
          space_name:   ${{ secrets.DO_SPACE_NAME   }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source:       lc.json
