name: Validate JSON 
on:
  push:
    branches: ['main']
    paths: ['lc.json']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.5.0
        with:
          comment: "true" # enable comment mode
          files: "lc.json"
